### ISSUE TITLE
Practica TestCase

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-entrevista_equipo-irving#3]
[Practica 2 Test case.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-entrevista_equipo-irving/files/12807782/Practica.2.Test.case.pdf)

**Comment by mel-16** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
